import "./admin.css";
import AdminHeader from "./admin/ui/AdminHeader";
import MenuBar from "./admin/ui/MenuBar";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <AdminHeader/>
        <MenuBar/>
        {children}</body>
    </html>
  )
}
