import { Inter } from "next/font/google";
import "./globals.css";
import HomeHeader from "./ui/HomeHeader";
import NextAuthProvider from "@/context/NextAuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <HomeHeader/>
          {children}
        </NextAuthProvider>
        </body>
    </html>
  );
}
